/**
 * PGVPT - API Offres touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DisponibiliteOffreResponse { 
    offreId: string;
    disponible: boolean;
    capaciteMax?: number;
    capaciteDisponible?: number;
    message?: string;
}

