/**
 * PGVPT - API Offres touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypePrestation = {
    Guide: 'GUIDE',
    Transport: 'TRANSPORT',
    Repas: 'REPAS',
    Hebergement: 'HEBERGEMENT',
    Visite: 'VISITE',
    Animation: 'ANIMATION',
    Location: 'LOCATION',
    Autre: 'AUTRE',
} as const;
export type TypePrestation = typeof TypePrestation[keyof typeof TypePrestation];

