package com.pgvpt.enums;

public enum TypeZone {
    ZONE_URBAINE_ET_CULTURELLE,
    ZONE_BALNEAIRE,
    ZONE_RURALE_ET_TERROIR,
    ZONE_AFFAIRES_ET_CONGRES,
    ZONE_RELIGIEUSE_ET_PELERINAGE,
    ZONE_RECREATIVE_ET_LOISIRS,
    ZONE_NATURELLE_PROTEGEE,
    AIRE_MARINE,
    PARC_NATIONAL,
    RESERVE_NATURELLE,
    ZONE_MONTAGNE,
    ZONE_TOURISTIQUE
}
