package com.pgvpt.enums;

public enum Role {
    ADMIN,
    GESTIONNAIRE,
    GESTIONNAIRE_PATRIMOINE,
    GESTIONNAIRE_TOURISME,
    GESTIONNAIRE_EVENEMENT,
    GESTIONNAIRE_RESERVATION,
    TOURISTE,
    PARTENAIRE
}
