/**
 * PGVPT - API Réservations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantCreate { 
    nom: string;
    prenom: string;
    telephone?: string;
    email?: string;
    age?: number;
}

