/**
 * PGVPT - API Réservations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Participant { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly reservationId: string;
    nom: string;
    prenom: string;
    telephone?: string;
    email?: string;
    age?: number;
}

