/**
 * PGVPT - API Réservations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Reservation } from './reservation';


export interface ReservationPage { 
    content: Array<Reservation>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

