/**
 * PGVPT - API Réservations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatutReservation } from './statut-reservation';
import { TypeRessource } from './type-ressource';


export interface Reservation { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly numero: string;
    readonly utilisateurId: string;
    typeRessource: TypeRessource;
    readonly ressourceId: string;
    dateReservation: string;
    nombrePersonnes: number;
    readonly montantTotal: number;
    readonly devise: string;
    statut: StatutReservation;
    readonly dateConfirmation?: string;
    readonly dateAnnulation?: string;
    readonly motifAnnulation?: string;
    commentaire?: string;
}
export namespace Reservation {
}


