/**
 * PGVPT - API Réservations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StatutReservation = {
    EnAttente: 'EN_ATTENTE',
    Confirmee: 'CONFIRMEE',
    Annulee: 'ANNULEE',
    Expiree: 'EXPIREE',
    Terminee: 'TERMINEE',
} as const;
export type StatutReservation = typeof StatutReservation[keyof typeof StatutReservation];

