/**
 * PGVPT - API Réservations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypeRessource = {
    Circuit: 'CIRCUIT',
    Activite: 'ACTIVITE',
    OffreTouristique: 'OFFRE_TOURISTIQUE',
    Evenement: 'EVENEMENT',
} as const;
export type TypeRessource = typeof TypeRessource[keyof typeof TypeRessource];

