/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Activite { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    /**
     * Code unique de l\'activité
     */
    code: string;
    /**
     * Libellé de l\'activité
     */
    libelle: string;
    description?: string;
    /**
     * Prix initial de référence de l\'activité
     */
    prixInitial: number;
    /**
     * Indique si l\'activité est active
     */
    actif?: boolean;
}

