/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CalculPrixCircuitResponse { 
    circuitId: string;
    /**
     * Prix total calculé à partir des prix des Etapes actives
     */
    prixTotal: number;
    devise: string;
    readonly calculeLe?: string;
}

