/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeCircuit } from './type-circuit';
import { NiveauDifficulte } from './niveau-difficulte';
import { StatutCircuit } from './statut-circuit';


export interface Circuit { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    nom: string;
    description?: string;
    type: TypeCircuit;
    zoneTouristiqueId: string;
    /**
     * Date de début de validité ou de programmation du circuit
     */
    dateDebut?: string | null;
    /**
     * Date de fin de validité ou de programmation du circuit. Doit être supérieure ou égale à dateDebut.
     */
    dateFin?: string | null;
    readonly statut?: StatutCircuit;
    dureeMinutes?: number;
    distanceKm?: number;
    niveauDifficulte?: NiveauDifficulte;
    actif?: boolean;
    readonly nombreEtapes?: number;
    readonly coutTotal?: number;
}
export namespace Circuit {
}


