/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EtapeOptimisee { 
    ordre: number;
    patrimoineId: string;
    activiteId: string;
    distanceDepuisPrecedenteKm?: number;
    dureeMinutes?: number;
    cout?: number;
}

