/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OptimisationItineraireRequest { 
    methode?: OptimisationItineraireRequest.MethodeEnum;
    latitudeDepart?: number;
    longitudeDepart?: number;
    latitudeArrivee?: number;
    longitudeArrivee?: number;
    dureeMaxMinutes?: number;
    poidsDistance?: number;
    poidsDuree?: number;
    poidsCout?: number;
}
export namespace OptimisationItineraireRequest {
    export const MethodeEnum = {
        DistanceMinimale: 'DISTANCE_MINIMALE',
        DureeMinimale: 'DUREE_MINIMALE',
        CoutMinimal: 'COUT_MINIMAL',
        Multicritere: 'MULTICRITERE',
    } as const;
    export type MethodeEnum = typeof MethodeEnum[keyof typeof MethodeEnum];
}


