/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrdreEtape { 
    etapeId: string;
    ordre: number;
}

