/**
 * PGVPT - Microservice Circuits Touristiques
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrdreEtape } from './ordre-etape';


export interface ReordonnerEtapesRequest { 
    etapes: Array<OrdreEtape>;
}

