/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Accessibilite { 
    accessiblePublic?: boolean;
    accessibilitePMR?: boolean;
    accesFauteuilRoulant?: boolean;
    accesTransportPublic?: boolean;
    parking?: boolean;
    guideDisponible?: boolean;
    guideAudio?: boolean;
    langueVisite?: Array<string>;
    accesEnfant?: boolean;
    conditionsAcces?: string;
    restrictions?: Array<string>;
}

