/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CollectionMusee { 
    id?: string;
    nom?: string;
    description?: string;
    nombreOeuvres?: number;
    periode?: string;
    origine?: string;
    themes?: Array<string>;
}

