/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const EtatConservation = {
    Excellent: 'EXCELLENT',
    Bon: 'BON',
    Moyen: 'MOYEN',
    Mauvais: 'MAUVAIS',
    Critique: 'CRITIQUE',
    Ruine: 'RUINE',
} as const;
export type EtatConservation = typeof EtatConservation[keyof typeof EtatConservation];

