/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Exposition { 
    id?: string;
    titre?: string;
    description?: string;
    dateDebut?: string;
    dateFin?: string;
    commissaire?: string;
    lieu?: string;
    expositionPermanente?: boolean;
    imageUrl?: string;
}

