/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JourSemaine } from './jour-semaine';


export interface HoraireOuverture { 
    jour: JourSemaine;
    ouvert?: boolean;
    heureOuverture?: string;
    heureFermeture?: string;
    pauseDebut?: string;
    pauseFin?: string;
    surReservation?: boolean;
    commentaire?: string;
}
export namespace HoraireOuverture {
}


