/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JourSemaine = {
    Lundi: 'LUNDI',
    Mardi: 'MARDI',
    Mercredi: 'MERCREDI',
    Jeudi: 'JEUDI',
    Vendredi: 'VENDREDI',
    Samedi: 'SAMEDI',
    Dimanche: 'DIMANCHE',
} as const;
export type JourSemaine = typeof JourSemaine[keyof typeof JourSemaine];

