/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NatureMonument = {
    MonumentHistorique: 'MONUMENT_HISTORIQUE',
    MonumentCommemoratif: 'MONUMENT_COMMEMORATIF',
    EdificeReligieux: 'EDIFICE_RELIGIEUX',
    EdificeColonial: 'EDIFICE_COLONIAL',
    EdificeAdministratif: 'EDIFICE_ADMINISTRATIF',
    Fortification: 'FORTIFICATION',
    Phare: 'PHARE',
    PorteHistorique: 'PORTE_HISTORIQUE',
    Mausolee: 'MAUSOLEE',
    Statue: 'STATUE',
    Autre: 'AUTRE',
} as const;
export type NatureMonument = typeof NatureMonument[keyof typeof NatureMonument];

