/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NatureSiteNaturel = {
    ParcNational: 'PARC_NATIONAL',
    ReserveNaturelle: 'RESERVE_NATURELLE',
    ReserveCommunautaire: 'RESERVE_COMMUNAUTAIRE',
    AireMarineProtegee: 'AIRE_MARINE_PROTEGEE',
    Foret: 'FORET',
    Mangrove: 'MANGROVE',
    Lac: 'LAC',
    Lagon: 'LAGON',
    Fleuve: 'FLEUVE',
    Cascade: 'CASCADE',
    Plage: 'PLAGE',
    Falaise: 'FALAISE',
    Desert: 'DESERT',
    Savane: 'SAVANE',
    ZoneHumide: 'ZONE_HUMIDE',
    Delta: 'DELTA',
    Autre: 'AUTRE',
} as const;
export type NatureSiteNaturel = typeof NatureSiteNaturel[keyof typeof NatureSiteNaturel];

