/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EtatConservation } from './etat-conservation';
import { Tarification } from './tarification';
import { Conservation } from './conservation';
import { GeolocalisationDTO } from './geolocalisation-dto';
import { Media } from './media';
import { Menace } from './menace';
import { Photo } from './photo';
import { CategoriePatrimoine } from './categorie-patrimoine';
import { Contact } from './contact';
import { Accessibilite } from './accessibilite';
import { PeriodeHistorique } from './periode-historique';
import { HoraireOuverture } from './horaire-ouverture';
import { StatutPatrimoine } from './statut-patrimoine';


export interface PatrimoineUpdate { 
    readonly id?: string;
    /**
     * Code métier unique du patrimoine
     */
    code?: string;
    nom: string;
    /**
     * Nom traditionnel ou nom local
     */
    nomLocal?: string;
    nomHistorique?: string;
    type: string;
    categorie: CategoriePatrimoine;
    sousCategorie?: string;
    periode?: PeriodeHistorique;
    siecle?: string;
    dateOuverture?: string;
    description: string;
    descriptionCourte?: string;
    historique?: string;
    importanceHistorique?: string;
    importanceCulturelle?: string;
    importanceTouristique?: string;
    valeurPatrimoniale?: string;
    valeurSpirituelle?: string;
    traditionsAssociees?: Array<string>;
    langues?: Array<string>;
    etatConservation?: EtatConservation;
    statut?: StatutPatrimoine;
    /**
     * Indique si le patrimoine bénéficie d\'un classement officiel
     */
    classePatrimoine?: boolean;
    referenceClassement?: string;
    dateClassement?: string;
    inscritUnesco?: boolean;
    nomSiteUnesco?: string;
    dateInscriptionUnesco?: string;
    protectionJuridique?: string;
    organismeGestionnaire?: string;
    proprietaire?: string;
    gestionnaire?: string;
    contact?: Contact;
    siteWeb?: string;
    email?: string;
    telephone?: string;
    accessibilite?: Accessibilite;
    tarification?: Tarification;
    horaires?: Array<HoraireOuverture>;
    photos?: Array<Photo>;
    medias?: Array<Media>;
    conservation?: Conservation;
    geolocalisation?: GeolocalisationDTO;
    menaces?: Array<Menace>;
    recommandationsVisiteur?: Array<string>;
    reglesVisite?: Array<string>;
    activitesTouristiques?: Array<string>;
    meilleurePeriodeVisite?: string;
    dureeVisiteEstimeeMinutes?: number;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly publishedAt?: string;
}
export namespace PatrimoineUpdate {
}


