/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PhotoCreate { 
    url: string;
    miniatureUrl?: string;
    titre?: string;
    description?: string;
    auteur?: string;
    datePrise?: string;
    droits?: string;
    licence?: string;
    photoPrincipale?: boolean;
    ordre?: number;
}

