/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StatutPatrimoine = {
    Brouillon: 'BROUILLON',
    EnValidation: 'EN_VALIDATION',
    Valide: 'VALIDE',
    Publie: 'PUBLIE',
    Archive: 'ARCHIVE',
} as const;
export type StatutPatrimoine = typeof StatutPatrimoine[keyof typeof StatutPatrimoine];

