/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Tarification { 
    gratuit?: boolean;
    tarifNormal?: number;
    devise?: string;
    tarifEnfant?: number;
    tarifEtudiant?: number;
    tarifResident?: number;
    tarifGroupe?: number;
    tarifGuide?: number;
    conditionsTarifaires?: string;
}

