/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypeMedia = {
    Photo: 'PHOTO',
    Video: 'VIDEO',
    Audio: 'AUDIO',
    Document: 'DOCUMENT',
    VisiteVirtuelle: 'VISITE_VIRTUELLE',
    Modele3D: 'MODELE_3D',
} as const;
export type TypeMedia = typeof TypeMedia[keyof typeof TypeMedia];

