/**
 * MS Patrimoine - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypePatrimoine = {
    SiteNaturel: 'SITE_NATUREL',
    Musee: 'MUSEE',
    Monument: 'MONUMENT',
} as const;
export type TypePatrimoine = typeof TypePatrimoine[keyof typeof TypePatrimoine];

