/**
 * PGVPT - API Événements
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Evenement } from './evenement';


export interface EvenementPage { 
    content?: Array<Evenement>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
}

