/**
 * PGVPT - API Événements
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeEvenement } from './type-evenement';
import { StatutEvenement } from './statut-evenement';


export interface Evenement { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    titre: string;
    description?: string;
    type: TypeEvenement;
    zoneTouristiqueId: string;
    patrimoineId?: string | null;
    organisateurActeurId: string;
    statut?: StatutEvenement;
    capaciteMax?: number;
    tarif?: number;
    devise?: string;
    reservationRequise?: boolean;
    langues?: Set<string>;
}
export namespace Evenement {
}


