/**
 * PGVPT - API Événements
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StatutEvenement = {
    Brouillon: 'BROUILLON',
    Programme: 'PROGRAMME',
    Ouvert: 'OUVERT',
    Complet: 'COMPLET',
    Termine: 'TERMINE',
    Annule: 'ANNULE',
} as const;
export type StatutEvenement = typeof StatutEvenement[keyof typeof StatutEvenement];

