/**
 * PGVPT - API Événements
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypeEvenement = {
    Festival: 'FESTIVAL',
    Concert: 'CONCERT',
    Exposition: 'EXPOSITION',
    Conference: 'CONFERENCE',
    Ceremonie: 'CEREMONIE',
    FeteCulturelle: 'FETE_CULTURELLE',
    Artisanat: 'ARTISANAT',
    Sport: 'SPORT',
    VisiteGuidee: 'VISITE_GUIDEE',
    Autre: 'AUTRE',
} as const;
export type TypeEvenement = typeof TypeEvenement[keyof typeof TypeEvenement];

