spring:
  application:
    # CORRECTION: L'ancien nom etait errone (copier-coller de patrimoine)
    # name: ms-patrimoine
    name: ms-media

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:9999}"