/**
 * PGVPT - MS Contenu API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StatutContenu = {
    Brouillon: 'BROUILLON',
    EnRevision: 'EN_REVISION',
    Valide: 'VALIDE',
    Publie: 'PUBLIE',
    Archive: 'ARCHIVE',
} as const;
export type StatutContenu = typeof StatutContenu[keyof typeof StatutContenu];

