/**
 * PGVPT - MS Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeMedia } from './type-media';


export interface MediaCreate { 
    patrimoineId: string;
    type: TypeMedia;
    nom: string;
    description?: string;
    url: string;
    mimeType?: string;
    tailleOctets?: number;
    langue?: string;
    auteur?: string;
    droitsUtilisation?: string;
    credit?: string;
    latitude?: number;
    longitude?: number;
}
export namespace MediaCreate {
}


