/**
 * PGVPT - MS Media API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypeMedia = {
    Photo: 'PHOTO',
    Video: 'VIDEO',
    Audio: 'AUDIO',
    Document: 'DOCUMENT',
    Panorama360: 'PANORAMA_360',
    Modele3D: 'MODELE_3D',
    Carte: 'CARTE',
    ArchiveNumerisee: 'ARCHIVE_NUMERISEE',
} as const;
export type TypeMedia = typeof TypeMedia[keyof typeof TypeMedia];

