server:
  port: 3002

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: ms-geolocalisation

  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    discovery:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/geolocalisationdb
    username: postgres
    password: "Thies@#1521"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: false