/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.pgvpt.api;

import com.pgvpt.dto.Conservation;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
@Tag(name = "Conservation", description = "Gestion de l'état et des actions de conservation")
public interface ConservationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /patrimoines/{id}/conservation : Obtenir les informations de conservation
     *
     * @param id Identifiant unique du patrimoine (required)
     * @return Informations de conservation (status code 200)
     */
    @Operation(
        operationId = "getConservation",
        summary = "Obtenir les informations de conservation",
        tags = { "Conservation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Informations de conservation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Conservation.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/patrimoines/{id}/conservation",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Conservation> getConservation(
        @Parameter(name = "id", description = "Identifiant unique du patrimoine", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"descriptionEtat\" : \"descriptionEtat\", \"budgetEstime\" : 3.616076749251911, \"dernierTravaux\" : \"dernierTravaux\", \"dateDerniersTravaux\" : \"2000-01-23\", \"recommandations\" : [ \"recommandations\", \"recommandations\" ], \"organismeConservation\" : \"organismeConservation\", \"dateEvaluation\" : \"2000-01-23\", \"evaluateur\" : \"evaluateur\", \"degradations\" : [ \"degradations\", \"degradations\" ], \"travauxNecessaires\" : [ \"travauxNecessaires\", \"travauxNecessaires\" ], \"causesDegradation\" : [ \"causesDegradation\", \"causesDegradation\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /patrimoines/{id}/conservation : Mettre à jour les informations de conservation
     *
     * @param id Identifiant unique du patrimoine (required)
     * @param conservation  (required)
     * @return Conservation mise à jour (status code 200)
     */
    @Operation(
        operationId = "updateConservation",
        summary = "Mettre à jour les informations de conservation",
        tags = { "Conservation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Conservation mise à jour", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Conservation.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/patrimoines/{id}/conservation",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Conservation> updateConservation(
        @Parameter(name = "id", description = "Identifiant unique du patrimoine", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "Conservation", description = "", required = true) @Valid @RequestBody Conservation conservation
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"descriptionEtat\" : \"descriptionEtat\", \"budgetEstime\" : 3.616076749251911, \"dernierTravaux\" : \"dernierTravaux\", \"dateDerniersTravaux\" : \"2000-01-23\", \"recommandations\" : [ \"recommandations\", \"recommandations\" ], \"organismeConservation\" : \"organismeConservation\", \"dateEvaluation\" : \"2000-01-23\", \"evaluateur\" : \"evaluateur\", \"degradations\" : [ \"degradations\", \"degradations\" ], \"travauxNecessaires\" : [ \"travauxNecessaires\", \"travauxNecessaires\" ], \"causesDegradation\" : [ \"causesDegradation\", \"causesDegradation\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
