/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Format d’erreur commun à l’ensemble des microservices PGVPT.
 */
export interface ApiError { 
    timestamp: string;
    status: number;
    code: string;
    error?: string;
    message: string;
    path: string;
    details?: Array<string>;
    traceId?: string;
}

