/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Coordonnée géographique en WGS84. Latitude comprise entre -90 et 90 et longitude entre -180 et 180.
 */
export interface Coordonnee { 
    latitude: number;
    longitude: number;
}

