/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypePatrimoine } from './type-patrimoine';


export interface FeaturePatrimoine { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    patrimoineId?: string;
    nom?: string;
    type?: TypePatrimoine;
    categorie?: string;
    latitude?: number;
    longitude?: number;
    icone?: string;
    couleur?: string;
    description?: string;
}
export namespace FeaturePatrimoine {
}


