/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Géométrie GeoJSON de type Point. Les coordonnées sont exprimées dans l’ordre [longitude, latitude].
 */
export interface GeoJsonPoint { 
    type: GeoJsonPoint.TypeEnum;
    /**
     * Coordonnées GeoJSON dans l’ordre [longitude, latitude].
     */
    coordinates: Array<number>;
}
export namespace GeoJsonPoint {
    export const TypeEnum = {
        Point: 'Point',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


