/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoJsonFeature } from './geo-json-feature';


export interface GeoJsonFeatureCollection { 
    type: GeoJsonFeatureCollection.TypeEnum;
    features: Array<GeoJsonFeature>;
}
export namespace GeoJsonFeatureCollection {
    export const TypeEnum = {
        FeatureCollection: 'FeatureCollection',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


