/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoJsonPoint } from './geo-json-point';


export interface GeoJsonFeature { 
    type: GeoJsonFeature.TypeEnum;
    geometry: GeoJsonPoint;
    properties: { [key: string]: any; };
}
export namespace GeoJsonFeature {
    export const TypeEnum = {
        Feature: 'Feature',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


