/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Geolocalisation { 
    readonly id: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    latitude: number;
    longitude: number;
    altitude?: number;
    precisionMetres?: number;
    adresse?: string;
    lieuDit?: string;
    repere?: string;
    systemeReference?: string;
    codeEpsg?: number;
    /**
     * Origine de la donnée de géolocalisation.
     */
    source?: Geolocalisation.SourceEnum;
    dateAcquisition?: string;
    methodeAcquisition?: Geolocalisation.MethodeAcquisitionEnum;
    niveauFiabilite?: Geolocalisation.NiveauFiabiliteEnum;
    zoneTouristiqueId?: string;
    villageId?: string | null;
    quartierId?: string | null;
    /**
     * Identifiant du patrimoine provenant de ms-patrimoine.
     */
    patrimoineId?: string | null;
    /**
     * Identifiant de l\'entreprise provenant de ms-entreprise.
     */
    entrepriseId?: string | null;
}
export namespace Geolocalisation {
    export const SourceEnum = {
        Gps: 'GPS',
        Administration: 'ADMINISTRATION',
        Sig: 'SIG',
        OpenData: 'OPEN_DATA',
        Import: 'IMPORT',
        Autre: 'AUTRE',
    } as const;
    export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];
    export const MethodeAcquisitionEnum = {
        Gps: 'GPS',
        ReleveTerrain: 'RELEVE_TERRAIN',
        Satellite: 'SATELLITE',
        Drone: 'DRONE',
        Geocodage: 'GEOCODAGE',
        ImportSig: 'IMPORT_SIG',
        Autre: 'AUTRE',
    } as const;
    export type MethodeAcquisitionEnum = typeof MethodeAcquisitionEnum[keyof typeof MethodeAcquisitionEnum];
    export const NiveauFiabiliteEnum = {
        Faible: 'FAIBLE',
        Moyen: 'MOYEN',
        Eleve: 'ELEVE',
        TresEleve: 'TRES_ELEVE',
    } as const;
    export type NiveauFiabiliteEnum = typeof NiveauFiabiliteEnum[keyof typeof NiveauFiabiliteEnum];
}


