/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Commune } from './commune';


export interface PageCommune { 
    content: Array<Commune>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
    first: boolean;
    last: boolean;
}

