/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaysUpdate { 
    nom: string;
    code: string;
    codeIso2?: string;
    codeIso3?: string;
    devise: string;
    codeDevise?: string;
    indicatifTelephonique?: string;
    langueOfficielle?: string;
    continent?: string;
    actif?: boolean;
}

