/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypePointAcces } from './type-point-acces';


export interface PointAccesCreate { 
    nom: string;
    type: TypePointAcces;
    description?: string;
    latitude: number;
    longitude: number;
    adresse?: string;
    accessiblePMR?: boolean;
    parkingDisponible?: boolean;
    transportPublic?: boolean;
}
export namespace PointAccesCreate {
}


