/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaysReference } from './pays-reference';


export interface Region { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    pays?: PaysReference;
    code: string;
    nom: string;
    codePostal?: string;
    description?: string;
}

