/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypeZone = {
    ZoneUrbaineEtCulturelle: 'ZONE_URBAINE_ET_CULTURELLE',
    ZoneBalneaire: 'ZONE_BALNEAIRE',
    ZoneRuraleEtTerroir: 'ZONE_RURALE_ET_TERROIR',
    ZoneAffairesEtCongres: 'ZONE_AFFAIRES_ET_CONGRES',
    ZoneReligieuseEtPelerinage: 'ZONE_RELIGIEUSE_ET_PELERINAGE',
    ZoneRecreativeEtLoisirs: 'ZONE_RECREATIVE_ET_LOISIRS',
    ZoneNaturelleProtegee: 'ZONE_NATURELLE_PROTEGEE',
    AireMarine: 'AIRE_MARINE',
    ParcNational: 'PARC_NATIONAL',
    ReserveNaturelle: 'RESERVE_NATURELLE',
    ZoneMontagne: 'ZONE_MONTAGNE',
    ZoneTouristique: 'ZONE_TOURISTIQUE',
} as const;
export type TypeZone = typeof TypeZone[keyof typeof TypeZone];

