/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypePointAcces = {
    EntreePrincipale: 'ENTREE_PRINCIPALE',
    EntreeSecondaire: 'ENTREE_SECONDAIRE',
    Parking: 'PARKING',
    Quai: 'QUAI',
    Embarcadere: 'EMBARCADERE',
    Gare: 'GARE',
    ArretBus: 'ARRET_BUS',
    Aeroport: 'AEROPORT',
    Port: 'PORT',
    CentreVisiteur: 'CENTRE_VISITEUR',
    Autre: 'AUTRE',
} as const;
export type TypePointAcces = typeof TypePointAcces[keyof typeof TypePointAcces];

