/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommuneReference } from './commune-reference';


export interface Village { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    commune?: CommuneReference;
    code: string;
    nom: string;
    description?: string;
}

