/**
 * MS Géolocalisation des patrimoines - API
 *
 * Contact: contact@pgvpt.sn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZoneGeographiqueRegion } from './zone-geographique-region';


export interface ZoneGeographique { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    code: string;
    nom: string;
    description?: string;
    regions: Array<ZoneGeographiqueRegion>;
    superficieKm2?: number;
    latitudeCentre?: number;
    longitudeCentre?: number;
    actif?: boolean;
}

